<a href="https://colab.research.google.com/github/zenc0derr/Machine-Learning-CSE305/blob/main/Lab_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Python Basics

In [ ]:
print("Sujith")

Sujith


In [ ]:
print (2+3)
a=20
print (a)
print(type(a))
a="hello"
print (len(a))

5
20
<class 'int'>
5


In [ ]:
x = 3
print (type(x)) # Prints "<type 'int'>"
print (x)
 # Prints "3"
print (x + 1 ) # Addition; prints "4"
print (x - 1 ) # Subtraction; prints "2"
print (x * 2)
 # Multiplication; prints "6"
print (x ** 2) # Exponentiation; prints "9"
x += 1
print (x) # Prints "4"
x *= 2
print (x ) # Prints "8"
y = 2.5
print (type(y)) # Prints "<type 'float'>"
print (y, y + 1, y * 2, y ** 2)

<class 'int'>
3
4
2
6
9
4
8
<class 'float'>
2.5 3.5 5.0 6.25


In [ ]:
s = "hello"
print (s.capitalize())
print (s.upper())
 # Convert a string to uppercase; prints "HELLO"
print (s.ljust(7,'*'))
 # Right-justify a string, padding with spaces; prints " hello"
print (s.center(7,"*"))
 # Center a string, padding with spaces; prints " hello "
print (s.replace('l', '(ell)')) # Replace all instances of one substring with another;
# prints "he(ell)(ell)o"
print( ' world  '.strip()) # Strip leading and trailing whitespace; prints "world"

Hello
HELLO
hello**
*hello*
he(ell)(ell)o
world


In [ ]:
a="JKLM"
for i in a:
  print(i+"ack")

Jack
Kack
Lack
Mack


# Reading Input

In [ ]:
a=int(input("Enter a number: ")) #Read input from user
#Condition
if a>10:
  print ("Number is greater than 10")
else:
  print ("Number is less than 10")

Enter a number: 100
Number is greater than 10


In [ ]:
a=10
if a>5:
  print ("a>5")
elif a>4:
  print("a>4")
else:
  print ("Not matching")
range(10)
for i in range(10):
  print (i)

a>5
0
1
2
3
4
5
6
7
8
9


# Functions

In [ ]:
def my_fun(x,y):
  print(x+y)
my_fun(10,20)
my_fun("10","20")

30
1020


In [ ]:
a=[] #Null list
a=[1,2,3,4.5,"Hello","50"]#is a list
print (type(a))
print (len(a))
print( a[0])
print (a[-1])
print (a[2:5])
a.append(100) #add new element at the end of list
print (a)
a.remove(2)#Remove second element

<class 'list'>
6
1
50
[3, 4.5, 'Hello']
[1, 2, 3, 4.5, 'Hello', '50', 100]


In [ ]:
a.append("append value")
print (a)
a.insert(3,"insert value")
print (a)

[1, 3, 4.5, 'Hello', '50', 100, 'append value']
[1, 3, 4.5, 'insert value', 'Hello', '50', 100, 'append value']


In [ ]:
nums = [0, 1, 2, 3, 4]
even_squares=[]
for x in nums:
  if x%2==0:
    even_squares.append(x**2)
print( even_squares)

[0, 4, 16]


In [ ]:
even_squares = [x ** 2 for x in nums if x % 2 == 0]
print (even_squares ) # Prints "[0, 4, 16]"

[0, 4, 16]


In [ ]:
a=list(range(1,25))
print(a[2:5])
print(a[-1])
print(a[1:5:2])
print(a[-3:-1])
print(a[:])
print(a[::])
print(a[::2])
print(a[::-1])

[3, 4, 5]
24
[2, 4]
[22, 23]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
[1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23]
[24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11, 10, 9, 8, 7, 6, 5, 4, 3, 2, 1]


# Set

In [ ]:
animals = {'cat', 'dog'}
print ('cat' in animals)
 # Check if an element is in a set; prints "True"
print ('fish' in animals ) # prints "False"
animals.add('fish')
 # Add an element to a set
print ('fish' in animals) # Prints "True"
print (len(animals))
 # Number of elements in a set; prints "3"
animals.add('cat')
print (len(animals) )
animals.remove('cat')
print (len(animals) )
# Adding an element that is already in the set does nothing
# Prints "3"
# Remove an element from a set
# Prints "2"

True
False
True
3
3
2


# Dictionary

In [ ]:
pos={}#empty dictionary
print (type(dict))
pos["Man"]="Noun"
pos["Play"]="Verb"
pos["Good"]="Adjective"
pos["Apple"]="Noun"
pos["Cricket"]="Noun"
pos["Cry"]="Verb"
print (pos)
#Print all the nouns in the dictionary
for w in pos:
  if(pos[w]=="Noun"):
    print (w) 

<class 'type'>
{'Man': 'Noun', 'Play': 'Verb', 'Good': 'Adjective', 'Apple': 'Noun', 'Cricket': 'Noun', 'Cry': 'Verb'}
Man
Apple
Cricket


# Tuple

In [ ]:
d = {(x, x + 1): x for x in range(10)} # Create a dictionary with tuple keys
t = (5, 6)
 # Create a tuple
print (type(t))
 # Prints "<type 'tuple'>"
print (d[t] )
 # Prints "5"
print (d[(1, 2)]) # Prints "1"

<class 'tuple'>
5
1


# File

In [48]:
file=open("newfile.txt","a")
print (type(file))
a="\nThis will be written to the file."
file.write(a)
file.close()

<class '_io.TextIOWrapper'>


In [49]:
fread=open("newfile.txt")
text=fread.readlines()
# words=text.split()
print( text)
# print (sorted(words))

['This will be written to the file.This will be written to the file.\n', 'This will be written to the file.']


# Python For Machine Learning

## Numpy - Numerical Python

In [79]:
import numpy as np

a = np.array([1,2,3])
print(type(a))
print(a)
print(a.ndim)
print(a.shape)
print(a[0])
a[0]=5
print(a)

<class 'numpy.ndarray'>
[1 2 3]
1
(3,)
1
[5 2 3]


In [83]:
b = np.array([[1,2,3],[4,5,6]])
print(b)
print(b.shape)
print(b[0,0],b[0,1],b[1,0])

[[1 2 3]
 [4 5 6]]
(2, 3)
1 2 4


In [90]:
a = np.zeros((2,2))
print(a)

b = np.ones((3,2,2))
print(b)

c = np.full((2,3),7)
print(c)

d = np.eye(2)
print(d)

e = np.random.random((2,2))
print(e)

[[0. 0.]
 [0. 0.]]
[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
[[7 7 7]
 [7 7 7]]
[[1. 0.]
 [0. 1.]]
[[0.09544752 0.74896781]
 [0.75275923 0.21474856]]


Array Slicing

In [92]:
a = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
b = a[:2,1:3]
print(b)
# A slice of an array is a view into the same data, so modifying it
# will modify the original array.
print(a[0,1])
b[0,0] = 69
print(a[0,1])

[[2 3]
 [6 7]]
2
69


## Array Math

In [102]:
#Basic mathematical functions operate elementwise on arrays, and are available both as operator
#overloads and as functions in the numpy module:
x = np.array([[1,2],[3,4]],dtype=np.float64)
y = np.array([[5,6],[7,8]],dtype=np.float64)

print(x,"\n")
print(y,"\n")


print("add")
#print(x+y)
print(np.add(x,y),"\n")

print("Subtract")
#print(y-x)
print(np.subtract(y,x),"\n")

print("Multiplication")
#print(x*y)
print(np.multiply(x,y),"\n")

print("Division")
#print(y/x)
print(np.divide(y,x),"\n")

print("Square Root")
print(np.sqrt(x),"\n")

[[1. 2.]
 [3. 4.]] 

[[5. 6.]
 [7. 8.]] 

add
[[ 6.  8.]
 [10. 12.]] 

Subtract
[[4. 4.]
 [4. 4.]] 

Multiplication
[[ 5. 12.]
 [21. 32.]] 

Division
[[0.2        0.33333333]
 [0.42857143 0.5       ]] 

Square Root
[[1.         1.41421356]
 [1.73205081 2.        ]] 

