# **19CSE305: MACHINE LEARNING LAB 2**

ROLL NUMBER: CB.EN.U4CSE20366

## Python Basic Exercises

1. Get the values P,t,R from user and calculate compound interest. Formula to calculate compound interest annually is given by: 
        A = P(1+R/100)*t
        CI = A – P
        Input : Principle, Time, Rate
        Output : Compound Interest
2. Given a list of strings (Entered by the user), write program to get a percentage share of each word in the strings list.
        percentage = (Occurrence of a word / Total words) * 100
3. Check if  the binary representation of a number is Palindrome or not. Given an integer ‘n’ (entered by the user), write a Python function that returns true if binary representation of 'x' is palindrome and false if not.
4. Write a program to check if all digits of a number divide it. Given a number n (entered by the user), find whether all digits of n divide it or not.
5. Given a list of numbers (entered by the user), write a program to find the second largest number in that list.
        Input: [1, 2, 3, 4 ,5]
        Output: 4

# Answers:

In [ ]:
#1
P = int(input("Enter the Interest: "))
T = int(input("Enter the Time: "))
R = int(input("Enter the Rate: "))

A = P*(1+(R/100))*T

print("Compound Interest: ",A-P)

Enter the Interest: 100
Enter the Time: 100
Enter the Rate: 100
Compound Interest:  19900.0


In [11]:
#2
import re
string = ""
while(True):
  string += input("Enter String: ")
  string += " "
  ch = input("Do y want to continue:(Y/N)")
  if(not(ch == "Y" or ch  =="y")):
      break
string = string.strip()
array = re.split(r"[ :\-]+", string)

Words = {}

for str in array:
  if str in Words:
    Words[str] += 1
  else:
    Words[str] = 1

total = 0
for str in Words:
  total += Words[str]

for str in Words:
  percent = (Words[str]/total)*100
  print("Percentage of the word ",str,"is: ",percent)


Enter String: Tejesh Kumar S
Do y want to continue:(Y/N)Y
Enter String: Tejesh
Do y want to continue:(Y/N)N
Percentage of the word  Tejesh is:  50.0
Percentage of the word  Kumar is:  25.0
Percentage of the word  S is:  25.0


In [39]:
#3
def checkPalindrome(num):
  s = format(num,'b')
  return s == s[::-1]

if checkPalindrome(int(input("Enter an number: "))):
  print("Binary of the number is a palindrome")
else:
  print("Binary of the number is not a palindrome")

Enter an number: 7
Binary of the number is a palindrome


In [4]:
#4

def main():
  num = input("Enter a number: ")
  for i in num:
    if(int(num)%int(i)==0):
      continue
    else:
      print("No")
      return
  print("Yes")


main()



Enter a number: 23
No


In [5]:
#5
list = []
n = int(input("Enter the number of inputs"))
for i in range(0,n):
  list.append(int(input()))

list.sort()
print(list[1])


Enter the number of inputs3
4
10
3
4


## Numpy Basic Exercises

1. Create a 3D array of shape 4*5*2 that contains random decimal numbers between 1 and 10.
2. Create a randomly created 1D array and Convert it to a 2D array with 2 rows.
3. Given a NumPy array of temperature values, convert the values of Centigrade degrees into Fahrenheit degrees. 
4. Write a NumPy program to count the number of dimensions, number of elements and number of bytes for each element in a given array.
5. Write a NumPy program to extract third and second elements of the first and second rows from a given (3x4) array

# Answers

In [16]:
#1
import numpy as np
a = np.random.randint(2,10,(4,5,2))
print(a)

[[[5 4]
  [9 6]
  [9 7]
  [5 5]
  [5 9]]

 [[8 5]
  [7 9]
  [7 5]
  [7 9]
  [4 6]]

 [[3 2]
  [2 5]
  [6 9]
  [4 7]
  [2 3]]

 [[2 6]
  [6 4]
  [3 9]
  [7 8]
  [9 6]]]


In [19]:
#2
b = np.random.rand(1,10)
b = b.reshape(2,5)
print(b)

[[0.38493598 0.27224691 0.01487867 0.83156513 0.19648383]
 [0.11245757 0.08052865 0.89035406 0.71760178 0.53946478]]


In [22]:
#3
celsius = np.random.randint(0,50,(1,100))
print(celsius)
farenheit = (9/5)*celsius + 32
print(farenheit)

[[35 46 47 34 40 16  7 40 43  5  7 35 40 35 48 15 48 22 42 19 34 27 42 24
   6 19 40 14 47 38 18 37 32 18 22 23 26 12 21  7 16 30 35 46  1 41 31  2
  36 33 34 16 16 45 12  0 43 24 44 27 24  6  0 37  2 32 32 26 42 12 48 38
  22 29  7  0 37  7 36 44 23 36  5 26 24  0  0 35 45 33 23 37 26 34 33  0
   9 40  4  7]]
[[ 95.  114.8 116.6  93.2 104.   60.8  44.6 104.  109.4  41.   44.6  95.
  104.   95.  118.4  59.  118.4  71.6 107.6  66.2  93.2  80.6 107.6  75.2
   42.8  66.2 104.   57.2 116.6 100.4  64.4  98.6  89.6  64.4  71.6  73.4
   78.8  53.6  69.8  44.6  60.8  86.   95.  114.8  33.8 105.8  87.8  35.6
   96.8  91.4  93.2  60.8  60.8 113.   53.6  32.  109.4  75.2 111.2  80.6
   75.2  42.8  32.   98.6  35.6  89.6  89.6  78.8 107.6  53.6 118.4 100.4
   71.6  84.2  44.6  32.   98.6  44.6  96.8 111.2  73.4  96.8  41.   78.8
   75.2  32.   32.   95.  113.   91.4  73.4  98.6  78.8  93.2  91.4  32.
   48.2 104.   39.2  44.6]]


In [28]:
#4
a = np.random.randint(1,10,(2,3,3))
print(a)
print("Arrays Dimension: ",a.ndim)
print("No of elements int the array: ",a.size)
print("Byte of an element in the array: ",a.itemsize)


[[[7 6 1]
  [2 5 3]
  [5 4 6]]

 [[8 3 7]
  [4 6 5]
  [4 2 8]]]
Arrays Dimension:  3
No of elements int the array:  18
Byte of an element in the array:  8


In [32]:
#5
a = np.random.randint(1,10,(3,4))
print(a)
print(a[0:2,1:3])

[[3 5 9 3]
 [1 4 1 5]
 [3 1 5 6]]
[[5 9]
 [4 1]]
