# The Slowness of Loops 

In [4]:
import numpy as np
np.random.seed(0)

def compute_reciprocals(values):
    output = np.empty(len(values))
    #print(output)
    for i in range(len(values)):
        output[i] = 1.0 / values[i]
    return output
    
values = np.random.randint(1, 10, size=5)
print(compute_reciprocals(values))

[0.16666667 1.         0.25       0.25       0.125     ]


# Introducing UFuncs

In [3]:
#performing an operation on the array, which will
#then be applied to each element.
print(1.0 / values)

[0.16666667 1.         0.25       0.25       0.125     ]


In [6]:
np.arange(5)/np.arange(1,6)

array([0.        , 0.5       , 0.66666667, 0.75      , 0.8       ])

In [7]:
x = np.arange(9).reshape((3, 3))
2 ** x

array([[  1,   2,   4],
       [  8,  16,  32],
       [ 64, 128, 256]])

# Exploring NumPy’s UFuncs

In [8]:
#Array arithmetic
x = np.arange(4)
print("x =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)

x = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


In [9]:
 print("-x = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2 = ", x % 2)

-x =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2 =  [0 1 0 1]


In [11]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

In [12]:
#Absolute value
abs(x)

array([0, 1, 2, 3])

In [15]:
#Trigonometric functions
theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [16]:
print("sin(theta) = ", np.sin(theta))
print("cos(theta) = ", np.cos(theta))
print("tan(theta) = ", np.tan(theta))

sin(theta) =  [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) =  [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) =  [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [23]:
#Exponents and logarithms
x = [1,2,3]
print("e^x:",np.exp(x))
print("2^x:",np.exp2(x))
print("3^x:",np.power(3,x))

e^x: [ 2.71828183  7.3890561  20.08553692]
2^x: [2. 4. 8.]
3^x: [ 3  9 27]


In [25]:
x = [1, 2, 4, 10]
print("x=", x)
print("ln(x) =", np.log(x))
print("log2(x) =", np.log2(x))
print("log10(x) =", np.log10(x))

x= [1, 2, 4, 10]
ln(x) = [0.         0.69314718 1.38629436 2.30258509]
log2(x) = [0.         1.         2.         3.32192809]
log10(x) = [0.         0.30103    0.60205999 1.        ]


In [27]:
#Specialized ufuncs
from scipy import special

# Advanced Ufunc Features

In [28]:
#Specifying output
x = np.arange(5)
y = np.empty(5)
np.multiply(x,10,out=y)
print(y)

[ 0. 10. 20. 30. 40.]


In [29]:
y = np.zeros(10)
np.power(2, x, out=y[::2])
print(y)

[ 1.  0.  2.  0.  4.  0.  8.  0. 16.  0.]


In [31]:
#Aggregates
x = np.arange(1,6)
np.add.reduce(x)

15

In [32]:
np.multiply.reduce(x)

120

In [33]:
np.add.accumulate(x)

array([ 1,  3,  6, 10, 15])

In [34]:
x = np.arange(1, 6)
np.multiply.outer(x, x)

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10],
       [ 3,  6,  9, 12, 15],
       [ 4,  8, 12, 16, 20],
       [ 5, 10, 15, 20, 25]])