# Introduction

In [2]:
import numpy as np

## Basics

In [3]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [5]:
#Dimension
print(a.ndim)
print(b.ndim)

1
2


In [6]:
#Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [7]:
#Get Type
print(a.dtype)

int64


In [8]:
#Specifying Type
c = np.array([1,2,3],dtype='int8')
print(c.dtype)

int8


In [9]:
#Get Size
print(a.size)

3


In [10]:
#Total Size
print(a.nbytes)

24


## Accessing/Changing specfic elements, rows, columns

In [11]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [12]:
#Get Specific Element [r,c]
print(a[0,3])
print(a[1,5])

4
12


In [13]:
#Get full row
print(a[0,:])
#Get Specific Column
print(a[:,0])

[1 2 3 4 5 6]
[1 7]


In [14]:
#Stepping
print(a[0,1:6:2])

[2 4 6]


In [15]:
#Changeing Elements
print(a[1,5])
a[1,5] = 0
print(a)

12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  0]]


In [16]:
a[:,3] = 20
print(a)

[[ 1  2  3 20  5  6]
 [ 7  8  9 20 11  0]]


3D arrays

In [17]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)
print("Dimension: ",b.ndim)
print("Shape: ",b.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension:  3
Shape:  (2, 2, 3)


In [18]:
#Getting 5
print(b[0,1,1])

5


In [19]:
print(b[:,1,:])

[[ 4  5  6]
 [10 11 12]]


In [20]:
#replace
print(b[1,1,:])
b[1,1,:] = [13,14,15]
print(b[1,1,:])

[10 11 12]
[13 14 15]


## Intializing Different Types of Arrays

In [21]:
# All 0 matrix
a = np.zeros((2,2,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [22]:
# All 1s Matrix
a = np.ones((2,2,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [23]:
#Other number
a = np.full((2,2,3),100)
print(a)

[[[100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]]]


In [24]:
#Random Decimal Number
np.random.rand(2,2,3)

array([[[0.95318068, 0.4156075 , 0.83894948],
        [0.31007557, 0.79649359, 0.99847733]],

       [[0.13477482, 0.79128751, 0.68923766],
        [0.54866205, 0.27295599, 0.1626848 ]]])

In [25]:
#Random Interger Value
np.random.randint(2,12,(2,4))

array([[3, 2, 5, 4],
       [9, 9, 4, 3]])

In [26]:
#Identity Matrix
print(np.identity(4,dtype='int8'))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [27]:
#Repeat Array
a = np.array([[1,2,3]])
print(np.repeat(a,3,axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [28]:
#Building Array
op = np.ones((5,5),dtype='int8')
print(op)

op[1:4,1:4]=0
print(op)

op[2,2]=9
print(op)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [29]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]


## Mathematics

In [30]:
a = np.array([1,2,3])

In [31]:
a + 2

array([3, 4, 5])

In [32]:
a - 2

array([-1,  0,  1])

In [33]:
a * 2

array([2, 4, 6])

In [35]:
a / 2

array([0.5, 1. , 1.5])

In [42]:
b = np.array([1,1,1])

a+b

array([[2, 2, 2],
       [2, 2, 2]])

In [37]:
#trignometry
np.sin(a)

array([0.84147098, 0.90929743, 0.14112001])

### Linear Algebra

In [44]:
#Matrix Multiplication
a = np.full((2,3),2)
print(a)

b = np.full((3,2),3)
print(b)

print(np.matmul(a,b))

[[2 2 2]
 [2 2 2]]
[[3 3]
 [3 3]
 [3 3]]
[[18 18]
 [18 18]]


In [45]:
#Determinant
c = np.identity(3)
np.linalg.det(c)

1.0

### Statistics

In [50]:
stats = np.array([[1,2,3],[4,5,6]])

print(np.min(stats,axis=0))
print(np.max(stats,axis=0))

[1 2 3]
[4 5 6]


In [52]:
np.sum(stats)

21