# Introduction

In [2]:
import numpy as np

## Basics

In [6]:
a = np.array([1,2,3])
print(a)

[1 2 3]


In [4]:
b = np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [7]:
#Dimension
print(a.ndim)
print(b.ndim)

1
2


In [8]:
#Shape
print(a.shape)
print(b.shape)

(3,)
(2, 3)


In [10]:
#Get Type
print(a.dtype)

int64


In [12]:
#Specifying Type
c = np.array([1,2,3],dtype='int8')
print(c.dtype)

int8


In [13]:
#Get Size
print(a.size)

3


In [14]:
#Total Size
print(a.nbytes)

24


## Accessing/Changing specfic elements, rows, columns

In [15]:
a = np.array([[1,2,3,4,5,6],[7,8,9,10,11,12]])
print(a)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [18]:
#Get Specific Element [r,c]
print(a[0,3])
print(a[1,5])

4
12


In [20]:
#Get full row
print(a[0,:])
#Get Specific Column
print(a[:,0])

[1 2 3 4 5 6]
[1 7]


In [24]:
#Stepping
print(a[0,1:6:2])

[2 4 6]


In [25]:
#Changeing Elements
print(a[1,5])
a[1,5] = 0
print(a)

12
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11  0]]


In [26]:
a[:,3] = 20
print(a)

[[ 1  2  3 20  5  6]
 [ 7  8  9 20 11  0]]


3D arrays

In [27]:
b = np.array([[[1,2,3],[4,5,6]],[[7,8,9],[10,11,12]]])
print(b)
print("Dimension: ",b.ndim)
print("Shape: ",b.shape)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
Dimension:  3
Shape:  (2, 2, 3)


In [28]:
#Getting 5
print(b[0,1,1])

5


In [29]:
print(b[:,1,:])

[[ 4  5  6]
 [10 11 12]]


In [33]:
#replace
print(b[1,1,:])
b[1,1,:] = [13,14,15]
print(b[1,1,:])

[10 11 12]
[13 14 15]


## Intializing Different Types of Arrays

In [36]:
# All 0 matrix
a = np.zeros((2,2,3))
print(a)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [37]:
# All 1s Matrix
a = np.ones((2,2,3))
print(a)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [38]:
#Other number
a = np.full((2,2,3),100)
print(a)

[[[100 100 100]
  [100 100 100]]

 [[100 100 100]
  [100 100 100]]]


In [39]:
#Random Decimal Number
np.random.rand(2,2,3)

array([[[0.7303835 , 0.04213038, 0.13970843],
        [0.40334819, 0.85793871, 0.36478443]],

       [[0.53230335, 0.6317988 , 0.97233553],
        [0.1023549 , 0.50464648, 0.88507003]]])

In [40]:
#Random Interger Value
np.random.randint(2,12,(2,4))

array([[10,  9,  8,  5],
       [ 4,  4, 10, 10]])

In [44]:
#Identity Matrix
print(np.identity(4,dtype='int8'))

[[1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [0 0 0 1]]


In [45]:
#Repeat Array
a = np.array([[1,2,3]])
print(np.repeat(a,3,axis=0))

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [52]:
#Building Array
op = np.ones((5,5),dtype='int8')
print(op)

op[1:4,1:4]=0
print(op)

op[2,2]=9
print(op)


[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]
[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 9 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


In [53]:
a = np.array([1,2,3])
b = a.copy()
b[0] = 100
print(a)

[1 2 3]
