# NumPy Array Attributes

In [1]:
import numpy as np

In [2]:
np.random.seed(0)
x1 = np.random.randint(10,size=6)
x2 = np.random.randint(10,size=(3,4))
x3 = np.random.randint(10,size=(3,4,5))

In [3]:
print("Dimension of x3:",x3.ndim)
print("shape of x3:",x3.shape)
print("no of cells of x3:",x3.size)

Dimension of x3: 3
shape of x3: (3, 4, 5)
no of cells of x3: 60


In [4]:
print("data type of x3 elements:",x3.dtype)
print("size of each element:",x3.itemsize)
print("total size of  of x3:",x3.nbytes)

data type of x3 elements: int64
size of each element: 8
total size of  of x3: 480


# Array Indexing: Accessing Single Elements

In [5]:
x1[1]

0

In [6]:
x1[-1]

9

In [7]:
x1[-2]

7

In [8]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [9]:
x2[0,1]

5

In [10]:
x2[-1,-3]

6

In [11]:
#modify value
x2[0,0]= 10

In [12]:
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

# Array Slicing: Accessing Subarrays

In [13]:
#x[start:stop:step]
x = np.arange(10)
x[::]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[:5]

array([0, 1, 2, 3, 4])

In [15]:
x[5:]

array([5, 6, 7, 8, 9])

In [16]:
x[4:7]

array([4, 5, 6])

In [17]:
x[::2]

array([0, 2, 4, 6, 8])

In [18]:
x[1::2]

array([1, 3, 5, 7, 9])

In [19]:
#step value is negative: the defaults for start and stop are swapped
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
x[5::-2]

array([5, 3, 1])

In [21]:
#Multidimensional subarrays
x2

array([[10,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [22]:
x2[:2,:3]

array([[10,  5,  2],
       [ 7,  6,  8]])

In [23]:
x2[:3,::2]

array([[10,  2],
       [ 7,  8],
       [ 1,  7]])

In [24]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 10]])

In [25]:
#Accessing array rows and columns
x2[:,0]

array([10,  7,  1])

In [26]:
#Subarrays as no-copy views
x2_sub = x2[:,0]
x2_sub

array([10,  7,  1])

In [30]:
x2_sub[1] = 8
x2_sub

array([10,  8,  1])

In [31]:
x2

array([[10,  5,  2,  4],
       [ 8,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [34]:
#Creating copies of arrays
x2_sub_copy = x2[:, 0].copy()
print(x2_sub_copy)

[10  8  1]


# Reshaping of Arrays

In [35]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [37]:
x = np.array([1,2,3])
x

array([1, 2, 3])

In [38]:
x.reshape((1,3))

array([[1, 2, 3]])

In [39]:
x[np.newaxis,:]

array([[1, 2, 3]])

In [42]:
x[:,np.newaxis]

array([[1],
       [2],
       [3]])

# Array Concatenation and Splitting

In [43]:
#Concatenation of arrays:  np.concatenate, np.vstack, and np.hstack
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [47]:
grid = np.array([[1, 2, 3],[4, 5, 6]])
np.concatenate([grid,grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [48]:
np.concatenate([grid,grid],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [50]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
[6, 5, 4]])
np.vstack([x,grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [51]:
y = np.array([[99],
[99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

In [54]:
# Splitting of arrays: np.split, np.hsplit, and np.vsplit
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [56]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [57]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [58]:
right, left = np.hsplit(grid, [2])
print(right)
print(left)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
