# Creating Arrays from Python Lists

In [2]:
import numpy as np

In [4]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [5]:
#upcasting
np.array([1,2,3.14,4])

array([1.  , 2.  , 3.14, 4.  ])

In [6]:
#explicit setting of types, dtype
np.array([1,2,3,4],dtype="float32")

array([1., 2., 3., 4.], dtype=float32)

In [11]:
# nested lists result in multidimensional arrays
np.array([range(i,i+3) for i in [1,4,7]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# Creating Arrays from Scratch

In [12]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [13]:
# Create a 3x5 floating-point array filled with 1s
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [19]:
# Create a 3x5x2 array filled with 3.14
np.full((3,5,2),3.14)

array([[[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]],

       [[3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14],
        [3.14, 3.14]]])

In [22]:
# Create an array filled with a linear sequence
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [26]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0,2,5)

array([0. , 0.5, 1. , 1.5, 2. ])

In [30]:
# Create a 3x3 array of uniformly distributed
np.random.random((3,3))

array([[0.93534545, 0.21750584, 0.84656922],
       [0.1625601 , 0.50773636, 0.91973807],
       [0.9505355 , 0.41916939, 0.93028432]])

In [28]:
# Create a 3x3 array of normally distributed random values
np.random.normal(0, 1, (3, 3))

array([[-1.3656443 , -1.20849174,  2.08519931],
       [-1.80720387, -1.39438944,  0.42008962],
       [ 1.54323041, -0.19752844,  1.41298021]])

In [31]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0,10,(3,3))

array([[5, 8, 2],
       [9, 1, 1],
       [7, 9, 0]])

In [32]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [43]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that
# memory location
np.empty(3)

array([1., 1., 1.])

# NumPy Standard Data Types

In [45]:
np.zeros(3,dtype=np.int16)

array([0, 0, 0], dtype=int16)